### ISSUE TITLE
[Feature request] support stack trace for rendering exception 

### ISSUE THREAD

**Issue by leo6104** [clbond/angular-ssr#15]
Thank you for developing awesome ssr project.

In my project, 'ng-render' command displayed an error message..

**[error] Failed to render application: SyntaxError: Unexpected token import =** 

With this message, i can't find out which file has problem.

https://github.com/clbond/angular-ssr/blob/master/source/bin/render.ts#L32

Can you support stack trace for rendering application exception?

**Comment by leo6104** [comment]
i can trace the erorr with modifying 'node_modules/angular-ssr/build/bin/render.js' (directly modify compiled js) 

i just add console.log.

                exception_1 = _a.sent();
                index_1.log.error("Failed to render application: " + exception_1.toString());
                console.log(exception_1);
                process.exitCode = 1;
                return [3 /*break*/, 4];

angulartics2 module is the root cause for me. I resolve the import error with removing angulartics2 dependency in ServerAppModule. (Only added to BrowserAppModule) 

But, another error is displayed..  **cssText.replace is not a function**
I think this is related to sass.

**Comment by leo6104** [comment]
the error 'cssText.replace is not a function' can be resolved with webpack - sass lodaer configuration. 

Install to-string-loader plugin ( npm install to-string-loader )
Add to-string-loader to webpack configuration. 

`{
  test: /\.scss$/,
  use: ['to-string-loader', 'css-loader', 'sass-loader'],
}`

**Comment by clbond** [comment]
Hi @leo6104, I believe all these issues should be resolved now that `ng-render` integrates with webpack. Your error should be gone now if you try with the latest version (`0.1.40`). If it is not, you can use the `--debug` flag on `ng-render` to get a full stack trace! Would you mind letting me know if your issue is indeed solved by the latest code? Thank you very much!

**Comment by leo6104** [comment]
@clbond Now i can find out the root cause!👍👍 
In my project, error message changed like this.
```
Error: Uncaught (in promise): ReferenceError: $ is not defined
ReferenceError: $ is not defined
    at new FroalaEditorDirective (/private/var/folders/3d/k80_sc0n7dd83nqzhfk09hph0000gn/T/bb76b99276c41/0.js:13306:26)
    at createClass (/Users/sangmin/WebstormProjects/mapia_ng2/packages/core/src/view/provider.ts:365:1)
    at createDirectiveInstance (/Users/sangmin/WebstormProjects/mapia_ng2/node_modules/@angular/core/bundles/core.umd.js:10634:37)
    at createViewNodes (/Users/sangmin/WebstormProjects/mapia_ng2/packages/core/src/view/view.ts:291:12)
    at callViewAction (/Users/sangmin/WebstormProjects/mapia_ng2/node_modules/@angular/core/bundles/core.umd.js:12354:13)
    at execComponentViewsAction (/Users/sangmin/WebstormProjects/mapia_ng2/node_modules/@angular/core/bundles/core.umd.js:12293:13)
    at createViewNodes (/Users/sangmin/WebstormProjects/mapia_ng2/node_modules/@angular/core/bundles/core.umd.js:12011:5)
    at createRootView (/Users/sangmin/WebstormProjects/mapia_ng2/node_modules/@angular/core/bundles/core.umd.js:11889:5)
    at callWithDebugContext (/Users/sangmin/WebstormProjects/mapia_ng2/packages/core/src/view/services.ts:645:1)
    at Object.debugCreateRootView [as createRootView] (/Users/sangmin/WebstormProjects/mapia_ng2/node_modules/@angular/core/bundles/core.umd.js:12481:12)
    at ComponentFactory_.create (/Users/sangmin/WebstormProjects/mapia_ng2/node_modules/@angular/core/bundles/core.umd.js:9825:46)
    at ComponentFactoryBoundToModule.create (/Users/sangmin/WebstormProjects/mapia_ng2/node_modules/@angular/core/bundles/core.umd.js:3434:29)
    at ViewContainerRef_.createComponent (/Users/sangmin/WebstormProjects/mapia_ng2/node_modules/@angular/core/bundles/core.umd.js:10025:62)
    at RouterOutlet.activateWith (/Users/sangmin/WebstormProjects/mapia_ng2/node_modules/@angular/router/bundles/router.umd.js:5334:40)
    at ActivateRoutes.placeComponentIntoOutlet (/Users/sangmin/WebstormProjects/mapia_ng2/node_modules/@angular/router/bundles/router.umd.js:4515:16)
    at ActivateRoutes.activateRoutes (/Users/sangmin/WebstormProjects/mapia_ng2/packages/router/src/router.ts:1375:1) =
```
the root cause is occured from 'declare $: jQueryStatic;' code in 3rd party library 'angular2-froala-editor'. 
Thank you very much!!
