### ISSUE TITLE
Error: Cannot find a generated NgFactory

### ISSUE THREAD

**Issue by buu700** [clbond/angular-ssr#27]
`ng-render` is consistently failing with the error `[error] Failed to render application: Error: Cannot find a generated NgFactory matching the name cyph.com/app.module with a symbol AppModule`, or `... cyph.com/app.module.ngfactory ... AppModuleNgFactory`.

I've tried the following with the same or similar results:

* Doing AOT via webpack + @ngtools/webpack

* Doing AOT via `ngc` directly

* Switching `--module` between relative and absolute paths

* Switching `--module` between app.module.ts and app.module.ngfactory.ts

* Omitting `--module` entirely

The file it's saying it can't find clearly exists, so I'm not sure what the problem is. The stack trace is below. Any ideas?

```
[info] Rendering application from source (working path: /tmp/38392951ec72b)
[error] Failed to render application: Error: Cannot find a generated NgFactory matching the name cyph.com/app.module with a symbol AppModule
    at CompilerException.ZoneAwareError (/node_modules/zone.js/dist/zone-node.js:915:33)
    at CompilerException.Exception [as constructor] (/node_modules/angular-ssr/source/exception.ts:6:5)
    at new CompilerException (/node_modules/angular-ssr/build/exception.js:64:42)
    at NgcModuleLoader.loadModule (/node_modules/angular-ssr/source/application/compiler/ngc/loader.ts:26:13)
    at NgcModuleLoader.load (/node_modules/angular-ssr/source/application/compiler/ngc/loader.ts:12:17)
    at /node_modules/angular-ssr/source/application/builder/from-source.ts:29:22
    at ZoneDelegate.invoke (/node_modules/zone.js/dist/zone-node.js:365:26)
    at Zone.run (/node_modules/zone.js/dist/zone-node.js:125:43)
    at /node_modules/zone.js/dist/zone-node.js:758:57
    at ZoneDelegate.invokeTask (/node_modules/zone.js/dist/zone-node.js:398:31)
    at Zone.runTask (/node_modules/zone.js/dist/zone-node.js:165:47)
    at drainMicroTaskQueue (/node_modules/zone.js/dist/zone-node.js:591:35)
    at ZoneTask.invoke (/node_modules/zone.js/dist/zone-node.js:464:25)
    at data.args.(anonymous function) (/node_modules/zone.js/dist/zone-node.js:1598:25)
    at _combinedTickCallback (internal/process/next_tick.js:86:20)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

**Comment by clbond** [comment]
Hmm. Your application does not use Angular CLI or webpack?

**Comment by buu700** [comment]
We aren't using the Angular CLI, but we do use webpack with the @ngtools AOT plugin (although as mentioned while debugging this I tried using `ngc` directly as well).

Just to give an idea of the different permutations of things I've tried, this is what the relevant part of the script currently looks like (have commented/uncommented different things, alternated between relative and absolute paths, etc., without any luck):

```
# sed -i 's|/platform-browser-dynamic|/platform-browser|g' "cyph.com/main.ts"
# sed -i 's|platformBrowserDynamic|platformBrowser|g' "cyph.com/main.ts"
# ngc -p .
# sed -i 's|\./app.module|\./app.module.ngfactory|g' "cyph.com/main.ts"
# sed -i 's|AppModule|AppModuleNgFactory|g' "cyph.com/main.ts"
# sed -i 's|bootstrapModule|bootstrapModuleFactory|g' "cyph.com/main.ts"
# ngc -p .

webpack --config "cyph.com/main.webpack.js"

ng-render \
	--debug \
	--template "/home/gibson/.build/cyph.com/index.html" \
	\ # --module "${PWD}/cyph.com/app.module.ts" \
	\ # --module "${PWD}/cyph.com/app.module.ngfactory.ts" \
	\ # --symbol AppModule \
	\ # --symbol AppModuleNgFactory \
	--project "${PWD}" \
	\ # --project "${PWD}/tsconfig.json" \
	--webpack "cyph.com/main.webpack.js" \
	--output "/home/gibson/.build/cyph.com"
```

**Comment by buu700** [comment]
Well, not exactly sure what was causing this, but I set up a branch with our project folder converted into the Angular CLI structure and it's resolved! I am running into #28 now, though.

**Comment by clbond** [comment]
@buu700 You can resolve the #28 issue by passing `--module app/app.module --symbol AppModule` (or whatever the right values are for your project). This is a workaround - I will investigate a proper fix. Can you give me access to this code?

**Comment by buu700** [comment]
Perfect, thanks! That's a much more convenient workaround than merging tsconfig files by hand.

Here's the Angular CLI version that's running into #28: https://github.com/cyph/cyph/tree/3f01d0ba8ab20226cd2173369ef1e1257423c1cb/cyph.com

And here's the pre-Angular-CLI version that was running into this issue (the exact state that triggers the problem is in the middle of a build script): https://github.com/cyph/cyph/blob/0f003462b99300d4fcae1326d1f0a60ed4eb0ca3/commands/build.sh#L587. The problem might be as simple as node_modules having been a symlink, since the Angular CLI had some issues building in the new branch until I replaced the node_modules symlink with a bind mount.

**Comment by clbond** [comment]
Hi @buu700. I've tried running the code in `cyph.com` and I believe it is failing due to the symbolic links inside the project.

This is where it's dying for me (on `ng build`): (note, `/Users/bond/cyph/cyph.com/src/js/node_modules/@types/node/index.d.ts` does not exist -- the right path is `/Users/bond/cyph/cyph.com/node_modules/@types/node/index.d.ts`

```
CREATE /Users/bond/cyph/cyph.com/src/js/node_modules/@types/node/index.d.ts undefined
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/Users/bond/cyph/cyph.com/node_modules/typescript/lib/typescript.js:14877:109)
    at parseSourceFileWorker (/Users/bond/cyph/cyph.com/node_modules/typescript/lib/typescript.js:14808:26)
    at Object.parseSourceFile (/Users/bond/cyph/cyph.com/node_modules/typescript/lib/typescript.js:14757:26)
    at Object.createSourceFile (/Users/bond/cyph/cyph.com/node_modules/typescript/lib/typescript.js:14612:29)
    at WebpackCompilerHost.getSourceFile (/Users/bond/cyph/cyph.com/node_modules/@ngtools/webpack/src/compiler_host.js:210:27)
    at findSourceFile (/Users/bond/cyph/cyph.com/node_modules/typescript/lib/typescript.js:64752:29)
    at processSourceFile (/Users/bond/cyph/cyph.com/node_modules/typescript/lib/typescript.js:64683:27)
    at /Users/bond/cyph/cyph.com/node_modules/typescript/lib/typescript.js:64793:17
    at Object.forEach (/Users/bond/cyph/cyph.com/node_modules/typescript/lib/typescript.js:1398:30)
    at processReferencedFiles (/Users/bond/cyph/cyph.com/node_modules/typescript/lib/typescript.js:64791:16)
    at findSourceFile (/Users/bond/cyph/cyph.com/node_modules/typescript/lib/typescript.js:64776:21)
    at processSourceFile (/Users/bond/cyph/cyph.com/node_modules/typescript/lib/typescript.js:64683:27)
    at /Users/bond/cyph/cyph.com/node_modules/typescript/lib/typescript.js:64793:17
    at Object.forEach (/Users/bond/cyph/cyph.com/node_modules/typescript/lib/typescript.js:1398:30)
    at processReferencedFiles (/Users/bond/cyph/cyph.com/node_modules/typescript/lib/typescript.js:64791:16)
    at findSourceFile (/Users/bond/cyph/cyph.com/node_modules/typescript/lib/typescript.js:64776:21)
```

**Comment by buu700** [comment]
Got it, that makes sense. The Angular CLI is replacing essentially a hand-rolled build system / project structure that felt a bit fragile in its interactions with Angular-related tooling at times, so I guess it's not surprising that our pre-Angular-CLI project would blow up coming in contact with something as complicated as angular-ssr. Probably not worth fixing this if it seems like it's not something anyone else is likely to ever run into (especially considering that even the Angular CLI doesn't like node_modules symlinks).

As far as the `ng build` error in the second commit I linked: it doesn't exist yet there (at that point we were kind of halfway switched over to the CLI), but there's another script that initialises each CLI project folder with bind mounts to node_modules and other shared folders, which would've been needed for any of the CLI commands to work.
