### ISSUE TITLE
Domino Element.prototype.outerHTML.set

### ISSUE THREAD

**Issue by buu700** [clbond/angular-ssr#31]
Edit: found the problem. Apparently domino doesn't like [DOMPurify](https://github.com/cure53/DOMPurify). Specifically, it needs to be able to use `Element.prototype.outerHTML.set`.

Haven't investigated to find out what's triggering it yet, but running `./node_modules/.bin/ng-render --debug` after `ng build` in my project produces the following error:

```
[error] Failed to render application: Error: NotYetImplemented
    at HTMLBodyElement.exports.nyi (/home/gibson/balls/cyph.com/node_modules/domino/lib/utils.js:41:9)
    at _initDocument (/tmp/b1ac8c65b477c/0.js:32221:28)
    at /tmp/b1ac8c65b477c/0.js:32244:23
    at factory (/tmp/b1ac8c65b477c/0.js:32248:10)
    at Object.<anonymous> (/tmp/b1ac8c65b477c/0.js:31814:62)
    at /tmp/b1ac8c65b477c/0.js:31814:79
    at Object.module.exports.module.exports.haveOpts (/tmp/b1ac8c65b477c/0.js:31821:2)
    at __webpack_require__ (/tmp/b1ac8c65b477c/0.js:21:30)
    at Object.module.exports.P (/tmp/b1ac8c65b477c/0.js:44067:68)
    at __webpack_require__ (/tmp/b1ac8c65b477c/0.js:21:30)
    at Object.<anonymous> (/tmp/b1ac8c65b477c/0.js:44261:69)
    at __webpack_require__ (/tmp/b1ac8c65b477c/0.js:21:30)
    at Object.<anonymous> (/tmp/b1ac8c65b477c/0.js:33211:75)
    at __webpack_require__ (/tmp/b1ac8c65b477c/0.js:21:30)
    at Object.<anonymous> (/tmp/b1ac8c65b477c/0.js:64320:18)
    at __webpack_require__ (/tmp/b1ac8c65b477c/0.js:21:30)
```

Package versions:

* @angular/*: 4.1.1

* @angular/cli: 1.0.2

* @angular/flex-layout: 2.0.0-beta.8

* @angular/material: 2.0.0-beta.3

* angular-ssr: 0.1.97

* domino: 1.0.44

* node: 7.10.0

* typescript: 2.3.2

* webpack: 2.5.1

**Comment by clbond** [comment]
Yes, that method is not implemented in domino. Can you link me the repo that this is happening in?

**Comment by clbond** [comment]
You are probably going to have to create a workaround and avoid using `outerHTML`. `domino` doesn't implement it and I am not confident that I can come up with a working implementation right now

**Comment by buu700** [comment]
Got it, thanks, I can work around it in this case then.
