### ISSUE TITLE
No NgModule metadata found for 't'

### ISSUE THREAD

**Issue by buu700** [clbond/angular-ssr#36]
Using angular-ssr 0.1.103 + Angular 4.1.3 + CLI 1.0.3 + rxjs 5.4.0 + zone.js 0.8.10 + TypeScript 2.3.2, the following is consistently reproducible when running ng-render. I also tried the two workarounds from #28 (tsconfig flattening, `--module`/`--symbol`) and got the same result.

Edit: also reproducible with 0.9.10.

```
gibson@2f931fc84db6:~/cyph/cyph.com$ ./node_modules/.bin/ng-render
[info] Rendering application from source (working path: /tmp/aa881fca662ab)
[error] Failed to render application: No NgModule metadata found for 't'. (use --debug to see a full stack trace)
gibson@2f931fc84db6:~/cyph/cyph.com$ ./node_modules/.bin/ng-render --debug
[info] Rendering application from source (working path: /tmp/cda25c7b0c1a2)
[error] Failed to render application: Error: No NgModule metadata found for 'AppModule'.
    at NgModuleResolver.resolve (/home/gibson/cyph/cyph.com/node_modules/@angular/compiler/@angular/compiler.es5.js:13884:12)
    at CompileMetadataResolver.getNgModuleMetadata (/home/gibson/cyph/cyph.com/node_modules/@angular/compiler/@angular/compiler.es5.js:14468:58)
    at JitCompiler._loadModules (/home/gibson/cyph/cyph.com/node_modules/@angular/compiler/@angular/compiler.es5.js:25635:61)
    at JitCompiler._compileModuleAndComponents (/home/gibson/cyph/cyph.com/node_modules/@angular/compiler/@angular/compiler.es5.js:25594:21)
    at JitCompiler.compileModuleAsync (/home/gibson/cyph/cyph.com/node_modules/@angular/compiler/bundles/compiler.umd.js:25561:23)
    at ServerPlatform.compileModule (/home/gibson/cyph/cyph.com/node_modules/angular-ssr/source/platform/platform.ts:33:21)
    at /home/gibson/cyph/cyph.com/node_modules/angular-ssr/source/application/builder/from-source.ts:31:22
    at ZoneDelegate.invoke (/home/gibson/cyph/cyph.com/node_modules/zone.js/dist/zone-node.js:381:26)
    at Zone.run (/home/gibson/cyph/cyph.com/node_modules/zone.js/dist/zone-node.js:141:43)
    at /home/gibson/cyph/cyph.com/node_modules/zone.js/dist/zone-node.js:805:57
    at ZoneDelegate.invokeTask (/home/gibson/cyph/cyph.com/node_modules/zone.js/dist/zone-node.js:414:31)
    at Zone.runTask (/home/gibson/cyph/cyph.com/node_modules/zone.js/dist/zone-node.js:181:47)
    at drainMicroTaskQueue (/home/gibson/cyph/cyph.com/node_modules/zone.js/dist/zone-node.js:574:35)
    at ZoneTask.invoke (/home/gibson/cyph/cyph.com/node_modules/zone.js/dist/zone-node.js:480:25)
    at data.args.(anonymous function) (/home/gibson/cyph/cyph.com/node_modules/zone.js/dist/zone-node.js:1370:25)
    at FSReqWrap.oncomplete (fs.js:114:15)
```

**Comment by clbond** [comment]
I think this is related to your project's configuration. This does not happen in either of the example applications that are in https://github.com/clbond/angular-ssr/tree/master/examples.

Based on the error message, probably what is happening is that multiple instances of `reflect-metdadata` are being loaded into the process and you are therefore losing the decorator metadata on all of your modules and components. You can probably fix this by altering your webpack configuration.

I would suggest trying to find what is different between your repository and the applications in the examples folder.

**Comment by buu700** [comment]
Hmm, well, this is just an Angular CLI project without a custom webpack configuration (our production build script `ng eject`s and adds some custom stuff, but this is just after a standard `ng build`). Could this be caused just by a library that our code depends on importing reflect-metadata?

Thanks, I'll take a look at those examples.

**Comment by buu700** [comment]
@clbond, found the problem, and it wasn't related to my project in particular (the same issue was reproducible with the cli example): `ng-render` doesn't like that my Docker image has node_modules located at `/node_modules`.

Is this something you think would be fixable in angular-ssr? I could work around it on my end, but it'd be a bit of a hassle, so I'd prefer to avoid it if the issue can be better mitigated here.

**Comment by clbond** [comment]
`node_modules` is located literally in `/` at the filesystem root?
