### ISSUE TITLE
Failed to render application: ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by gaithoben** [clbond/angular-ssr#41]
I was trying the application. I am using Angular 4.1.0 and Jquery 3.2.1. Everything runs fine with the Angular CLI. But When i try ./node_modules/.bin/ng-render. I get an error: 

**Failed to render application: ReferenceError: jQuery is not defined**
Any suggestions?

**Comment by clbond** [comment]
Yes, can you run `ng-render` with the `--debug` flag and paste the entire call stack that it prints out? Probably whichever .ts module is referencing jQuery is not `import`ing it.

**Comment by gaithoben** [comment]
clbond,

Please check the print out:

[info] Rendering application from source (working path: /var/folders/qw/fy6pdj413xn4lvnqt__2lyw40000gn/T/f36ba326c3a83) =
[error] Failed to render application: ReferenceError: jQuery is not defined
    at Object.module.exports.installedModules (/private/var/folders/qw/fy6pdj413xn4lvnqt__2lyw40000gn/T/f36ba326c3a83/0.js:90870:13052)
    at __webpack_require__ (/private/var/folders/qw/fy6pdj413xn4lvnqt__2lyw40000gn/T/f36ba326c3a83/0.js:21:30)
    at Object.<anonymous> (/private/var/folders/qw/fy6pdj413xn4lvnqt__2lyw40000gn/T/f36ba326c3a83/0.js:29702:116)
    at __webpack_require__ (/private/var/folders/qw/fy6pdj413xn4lvnqt__2lyw40000gn/T/f36ba326c3a83/0.js:21:30)
    at Object.module.exports.c (/private/var/folders/qw/fy6pdj413xn4lvnqt__2lyw40000gn/T/f36ba326c3a83/0.js:30079:76)
    at __webpack_require__ (/private/var/folders/qw/fy6pdj413xn4lvnqt__2lyw40000gn/T/f36ba326c3a83/0.js:21:30)
    at Object.<anonymous> (/private/var/folders/qw/fy6pdj413xn4lvnqt__2lyw40000gn/T/f36ba326c3a83/0.js:36204:96)
    at __webpack_require__ (/private/var/folders/qw/fy6pdj413xn4lvnqt__2lyw40000gn/T/f36ba326c3a83/0.js:21:30)
    at Object.<anonymous> (/private/var/folders/qw/fy6pdj413xn4lvnqt__2lyw40000gn/T/f36ba326c3a83/0.js:33020:72)
    at __webpack_require__ (/private/var/folders/qw/fy6pdj413xn4lvnqt__2lyw40000gn/T/f36ba326c3a83/0.js:21:30)
    at Object.<anonymous> (/private/var/folders/qw/fy6pdj413xn4lvnqt__2lyw40000gn/T/f36ba326c3a83/0.js:93402:18)
    at __webpack_require__ (/private/var/folders/qw/fy6pdj413xn4lvnqt__2lyw40000gn/T/f36ba326c3a83/0.js:21:30)
    at /private/var/folders/qw/fy6pdj413xn4lvnqt__2lyw40000gn/T/f36ba326c3a83/0.js:67:18
    at Object.<anonymous> (/private/var/folders/qw/fy6pdj413xn4lvnqt__2lyw40000gn/T/f36ba326c3a83/0.js:70:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19) =

**Comment by clbond** [comment]
I think you are missing an `import jQuery = require('jquery')` somewhere
