### ISSUE TITLE
ng-render: Cannot read property 'title' of undefined 

### ISSUE THREAD

**Issue by wnabil** [clbond/angular-ssr#55]
i copied the example/cli and put my source code 
then installed my dependencies 
i almost disabled everything in my application to fix this error but sadly no luck.

`[error] Fatal exception encountered: TypeError: Cannot read property 'title' of undefined 0l
[error] Failed to render application: Error: Fatal renderer exception: TypeError: Cannot read property 'title' of undefined
    at SafeSubscriber._error (/home/orange/Desktop/projects/maker/maker-front/node_modules/angular-ssr/source/application/builder/prerenderer.ts:26:20)
    at SafeSubscriber.__tryOrUnsub (/home/orange/Desktop/projects/maker/maker-front/node_modules/rxjs/src/Subscriber.ts:254:10)
    at SafeSubscriber.error (/home/orange/Desktop/projects/maker/maker-front/node_modules/rxjs/src/Subscriber.ts:216:16)
    at Subscriber._error (/home/orange/Desktop/projects/maker/maker-front/node_modules/rxjs/src/Subscriber.ts:139:22)
    at Subscriber.error (/home/orange/Desktop/projects/maker/maker-front/node_modules/rxjs/src/Subscriber.ts:109:12)
    at SafeSubscriber.__tryOrUnsub (/home/orange/Desktop/projects/maker/maker-front/node_modules/rxjs/src/Subscriber.ts:254:10)
    at SafeSubscriber.error (/home/orange/Desktop/projects/maker/maker-front/node_modules/rxjs/src/Subscriber.ts:216:16)
    at Subscriber._error (/home/orange/Desktop/projects/maker/maker-front/node_modules/rxjs/src/Subscriber.ts:139:22)
    at Subscriber.error (/home/orange/Desktop/projects/maker/maker-front/node_modules/rxjs/src/Subscriber.ts:109:12)
    at ReplaySubject.Subject.error (/home/orange/Desktop/projects/maker/maker-front/node_modules/rxjs/src/Subject.ts:77:15)
    at ApplicationImpl.<anonymous> (/home/orange/Desktop/projects/maker/maker-front/node_modules/angular-ssr/source/application/builder/impl/application.ts:81:19)
    at step (/home/orange/Desktop/projects/maker/maker-front/node_modules/angular-ssr/build/application/builder/impl/application.js:31:23)
    at Object.throw (/home/orange/Desktop/projects/maker/maker-front/node_modules/angular-ssr/build/application/builder/impl/application.js:12:53)
    at rejected (/home/orange/Desktop/projects/maker/maker-front/node_modules/angular-ssr/build/application/builder/impl/application.js:4:65)
    at ZoneDelegate.invoke (/home/orange/Desktop/projects/maker/maker-front/node_modules/zone.js/dist/zone-node.js:391:26)
    at Zone.run (/home/orange/Desktop/projects/maker/maker-front/node_modules/zone.js/dist/zone-node.js:141:43) 0l`

**Comment by wnabil** [comment]
fixed
`rm -R node_modules
rm package-lock.json
npm cache clear
npm install`
